---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-tls-enabled-rs
spec:
  type: ReplicaSet

  members: 3
  version: 4.0.4-ent

  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials

  # look into `replica-set-persistent-volumes.yaml` for an example on how to use
  # Kubernetes Persistent Volumes in your MDB deployment.
  persistent: false

  # This will create a TLS enabled Replica Set, which means that all the traffic
  # between members of the Replica Set and clients, will be encrypted using TLS
  # certificates.
  security:
    # The operator will look for a secret name mdb-my-tls-enabled-rs-cert
    certsSecretPrefix: mdb
    tls:
      ca: custom-ca
      enabled: true

  # The default TLS mode is 'requireTLS' but it can be customized using the
  # the `additionalMongodConfig` structure. Please find more information here:
  # https://docs.mongodb.com/manual/reference/configuration-options/#net.ssl.mode
  additionalMongodConfig:
    net:
      ssl:
        mode: "preferSSL"
