# provide statefulset override per cluster
---
apiVersion: mongodb.com/v1
kind: MongoDBMulti
metadata:
  name: multi-replica-set
spec:
  version: 4.4.0-ent
  type: ReplicaSet
  persistent: false
  duplicateServiceObjects: false
  credentials: my-credentials
  opsManager:
    configMapRef:
      name: my-project
  clusterSpecList:
    clusterSpecs:
      - clusterName: cluster1.mongokubernetes.com
        members: 2
        statefulSet:
          spec:
            template:
              spec:
                containers:
                - name: sidecar1
                  image: busybox
                  command: ["sleep"]
                  args: [ "infinity" ]
      - clusterName: cluster2.mongokubernetes.com
        members: 1
        statefulSet:
          spec:
            template:
              spec:
                containers:
                - name: sidecar2
                  image: busybox
                  command: ["sleep"]
                  args: [ "infinity" ]
      - clusterName: cluster3.mongokubernetes.com
        members: 1
        statefulSet:
          spec:
            template:
              spec:
                containers:
                - name: sidecar3
                  image: busybox
                  command: ["sleep"]
                  args: [ "infinity" ]
