---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  replicas: 1
  version: 5.0.5

  adminCredentials: ops-manager-admin-secret

  applicationDatabase:
    members: 3
    version: 4.4.11-ent


  # The statefulSet entry will modify the way the StatefulSet holding the
  # Ops Manager and Backup Daemon Pods will be created. In this case we can
  # specify a non-default SecurityContext.
  statefulSet:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 5000
            runAsUser: 5000
