---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-backup
spec:
  replicas: 1
  version: 4.4.1
  adminCredentials: ops-manager-admin-secret

  # optional. Enabled by default
  # Allows to configure backup in Ops Manager
  backup:
    enabled: true
    # optional. Configured by default if backup is enabled.
    # Configures Head db storage parameters
    headDB:
      # optional. Default storage is 30G
      storage: 50G
      # optional
      labelSelector:
        matchLabels:
          app: "my-app"
    # Configures the list of Oplog Store Configs
    opLogStores:
      - name: oplog1
        # reference to MongoDB Custom Resource. The Operator watches changes in it and updates Oplog configuration
        # in Ops Manager
        mongodbResourceRef:
          name: om-mongodb-oplog
        # optional. Specify if Oplog database has SCRAM-SHA authentication enabled
        mongodbUserRef:
          name: admin-user
    # Configures the list of S3 Snapshot Configs. Application database is used as a database for S3 metadata
    # by default
    # Note, that either S3 Snapshot or Blockstore config needs to be specified to backup MongoDB deployments
    s3Stores:
      - name: s3store1
        # the name of the secret which contains aws credentials
        s3SecretRef:
          name: my-aws-creds
        s3BucketEndpoint: s3.us-east-1.amazonaws.com
        s3BucketName: my-bucket-name
        pathStyleAccessEnabled: true
    # Configures the list of Blockstore Configs
    blockStores:
      - name: blockStore1
        # reference to MongoDB Custom Resource. The Operator watches changes in it and updates Blockstore configuration
        # in Ops Manager
        mongodbResourceRef:
          name: my-mongodb-blockstore

  applicationDatabase:
    members: 3
    version: 4.2.6-ent
