apiVersion: constraints.gatekeeper.sh/v1beta1
kind: MongoDBAllowedVersions
metadata:
  name: mongodb-allowed-versions-only
spec:
  match:
    kinds:
      - apiGroups: ["mongodb.com"]
        kinds: ["MongoDB"]
