apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set-pod-template
spec:
  members: 3
  version: 4.2.2-ent
  type: ReplicaSet
  opsManager:
    configMapName:
      name: my-project
  credentials: my-credentials

  podSpec:
    memory: 512M
    # 'podTemplate' allows to set custom fields in PodTemplateSpec (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podtemplatespec-v1-core)
    # for the Database StatefulSet.
    podTemplate:
      spec:
        # This container will be added to each pod as a sidecar
        containers:
          - name: standalone-sidecar
            image: busybox
            command: ["sleep"]
            args: [ "infinity" ]
            resources:
              limits:
                cpu: "1"
              requests:
                cpu: 500m

