apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set-pod-template
spec:
  members: 3
  version: 4.2.2-ent
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: my-project

  credentials: my-credentials

  podSpec:
    # `podTemplate` allows to set custom fields in PodTemplateSpec for the
    # Database Pods.
    # For more information see:
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podtemplatespec-v1-core
    podTemplate:
      spec:
        containers:
        - name: mongodb-enterprise-database
          # For more information about Pod and container resource management, see:
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: "0.8"
              memory: 1G

        # Another container will be added to each pod as a sidecar.
        - name: standalone-sidecar
          image: busybox
          command: ["sleep"]
          args: [ "infinity" ]
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: 500m
