apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-sharded-cluster-pod-template
spec:
  type: ShardedCluster
  version: 4.0.14-ent

  shardCount: 1
  mongodsPerShardCount: 1
  mongosCount: 1
  configServerCount: 1

  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials

  configSrvPodSpec:
    podAntiAffinityTopologyKey: nodeId
    podTemplate:
      spec:
        terminationGracePeriodSeconds: 120

        # `podTemplate.spec.containers[].resources` should be specified, otherwise WiredTiger
        # cache won't be calculated properly by MongoDB daemon.
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "0.8"
                memory: 1G

        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  # Note, that this topology key will overwrite the antiAffinity
                  # topologyKey set by the Operator from
                  # 'spec.configSrvPodSpec.podAntiAffinityTopologyKey'.
                  topologyKey: "failure-domain.beta.kubernetes.io/zone"
                weight: 30

  mongosPodSpec:
    podTemplate:
      spec:
        restartPolicy: Never
        serviceAccountName: the-custom-user

        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "0.8"
                memory: 1G

  shardPodSpec:
    podTemplate:
      metadata:
        annotations:
          key1: value1
      spec:
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "0.8"
                memory: 1G
        tolerations:
          - key: "key"
            operator: "Exists"
            effect: "NoSchedule"
