apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-standalone-pod-template
spec:
  version: 4.2.2-ent
  type: Standalone
  opsManager:
    configMapName:
      name: my-project
  credentials: my-credentials
  podSpec:
    podTemplate:
      spec:
        # This container will be added to each pod as a sidecar
        containers:
          - name: standalone-sidecar
            image: busybox
            command: ["sleep"]
            args: [ "infinity" ]
            resources:
              limits:
                cpu: "1"
              requests:
                cpu: 500m
