name: mongodb-enterprise-operator
description: MongoDB Kubernetes Enterprise Operator
version: 1.6.0
kubeVersion: '>=1.13-0'
keywords:
- mongodb
- database
- nosql
home: https://github.com/mongodb/mongodb-enterprise-kubernetes
maintainers:
- name: Cloud Team
