name: mongodb-enterprise-operator
description: MongoDB Kubernetes Enterprise Operator
version: 1.5.2
kubeVersion: '>=1.13'
keywords:
- mongodb
- database
- nosql
home: https://github.com/mongodb/mongodb-enterprise-kubernetes
maintainers:
- name: Cloud Team
