# Create the CustomerResourceDefinition for MongoDB custom types.
createCrds: true

# Name of the Namespace to use
namespace: mongodb

# OpenShift manages security context on its own
managedSecurityContext: true

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: enterprise-operator

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: 1.5.0

database:
  name: enterprise-database

opsManager:
  name: mongodb-enterprise-ops-manager

initOpsManager:
  name: mongodb-enterprise-init-ops-manager
  version: 1.0.0

appDb:
  name: mongodb-enterprise-appdb

initAppDb:
  name: mongodb-enterprise-init-appdb
  version: 1.0.0

registry:
  # The pull secret must be specified
  imagePullSecrets:
  pullPolicy: Always
  operator: registry.connect.redhat.com/mongodb
  initOpsManager: registry.connect.redhat.com/mongodb
  opsManager: registry.connect.redhat.com/mongodb
  initAppDb: registry.connect.redhat.com/mongodb
  appDb: registry.connect.redhat.com/mongodb

# Set this to true if the operator will require Kubernetes CA
# infrastructure to generate TLS certificates.
needsCAInfrastructure: true
