# Name of the Namespace to use
namespace: mongodb

# OpenShift manages security context on its own
managedSecurityContext: true

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: enterprise-operator

  # Name of the deployment of the operator pod
  deployment_name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: 1.7.0

  # The Custom Resources that will be watched by the Operator. Needs to be changed if only some of the CRDs are installed
  watchedResources:
  - mongodb
  - opsmanagers
  - mongodbusers

database:
  name: enterprise-database

opsManager:
  name: mongodb-enterprise-ops-manager

initOpsManager:
  name: mongodb-enterprise-init-ops-manager
  version: 1.0.1

appDb:
  name: mongodb-enterprise-appdb

initAppDb:
  name: mongodb-enterprise-init-appdb
  version: 1.0.2

registry:
  # The pull secret must be specified
  imagePullSecrets:
  pullPolicy: Always
  operator: registry.connect.redhat.com/mongodb
  initOpsManager: registry.connect.redhat.com/mongodb
  opsManager: registry.connect.redhat.com/mongodb
  initAppDb: registry.connect.redhat.com/mongodb
  appDb: registry.connect.redhat.com/mongodb

# Set this to true if the operator will require Kubernetes CA
# infrastructure to generate TLS certificates.
needsCAInfrastructure: true

# Set this to false to disable subresource utilization
# It might be required on some versions of Openshift
subresourceEnabled: true
