# Create the CustomerResourceDefinition for MongoDB custom types.
createCrds: true

# Name of the Namespace to use
namespace: mongodb

# OpenShift manages security context on its own
managedSecurityContext: true

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: enterprise-operator

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: 1.4.1

database:
  name: enterprise-database

opsManager:
  name: mongodb-enterprise-ops-manager

appDb:
  name: mongodb-enterprise-appdb

registry:
  # The pull secret must be specified
  imagePullSecrets:
  pullPolicy: Always
  repository: registry.connect.redhat.com/mongodb

# Set this to true if the operator will require Kubernetes CA
# infrastructure to generate TLS certificates.
needsCAInfrastructure: true
