apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set-options
spec:
  members: 3
  version: 4.2.8-ent
  type: ReplicaSet
  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials
  persistent: true
  # optional. Allows to pass custom MongoDB process configuration
  additionalMongodConfig:
    systemLog:
      logAppend: true
      verbosity: 4
    operationProfiling:
      mode: slowOp
