apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-sharded-cluster-options
spec:
  version: 4.2.8-ent
  type: ShardedCluster
  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials
  persistent: true
  shardCount: 2
  mongodsPerShardCount: 3
  mongosCount: 2
  configServerCount: 1
  mongos:
    # optional. Allows to pass custom configuration for mongos processes
    additionalMongodConfig:
      systemLog:
        logAppend: true
        verbosity: 4
  configSrv:
    # optional. Allows to pass custom configuration for Config Server mongod processes
    additionalMongodConfig:
      operationProfiling:
        mode: slowOp
  shard:
    additionalMongodConfig:
    # optional. Allows to pass custom configuration for Shards mongod processes
      storage:
        journal:
          commitIntervalMs: 50
