#
# This sample "Project" file will configure x509 client authentication.
# Please refer to the Ops Manager documentation for more information
# about this feature:
# - https://docs.opsmanager.mongodb.com/current/tutorial/enable-x509-authentication-for-group
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-x509-enabled-project
data:
  projectName: My Ops/Cloud Manager Project
  baseUrl: http://my-ops-cloud-manager-url
