#
# This sample "Project" file will configure x509 client authentication.
# Please refer to the Ops Manager documentation for more information
# about this feature:
# - https://docs.opsmanager.mongodb.com/current/tutorial/enable-x509-authentication-for-group
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-x509-enabled-project
data:
  projectName: My Ops/Cloud Manager Project
  baseUrl: http://my-ops-cloud-manager-url

  # Enable x509 authentication at the Project level.
  authenticationMode: x509

  # If enabling x509 authentication, the `credentials` attribute need to be supplied as well.
  # This is the same one used when creating a `MongoDB` resource.
  credentials: my-credentials
