---
apiVersion: mongodb.com/v1beta1
kind: MongoDbReplicaSet
metadata:
  name: my-replica-set
  namespace: mongodb
spec:
  members: 3
  version: 3.6.5
  # persistent: false will create stateful set pods without persistent volumes - it's convenient for testing. true by default
  persistent: false

  project: my-project
  credentials: my-credentials
