---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-tls-standalone
spec:
  version: 4.0.0

  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials
  type: Standalone

  persistent: true

  # This will create a TLS enabled Standalone which means that the
  # traffic will be encrypted using TLS certificates. These
  # certificates will be generated on the fly by the operatror using
  # the Kubernetes CA.
  # Please refer to Kubernetes TLS Documentation on how to approve these certs:
  #
  # https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/
  #
  security:
    tls:
      enabled: true
