{{ if eq .Values.createCrds true }}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodb.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDB
    plural: mongodb
    shortNames:
    - mdb
    singular: mongodb
  additionalPrinterColumns:
    - name: Type
      type: string
      description: "The type of MongoDB deployment. One of 'ReplicaSet', 'ShardedCluster' and 'Standalone'."
      JSONPath: .spec.type
    - name: State
      type: string
      description: The current state of the MongoDB deployment.
      JSONPath: .status.phase
    - name: Version
      type: string
      description: The version of MongoDB.
      JSONPath: .spec.version
    - name: Age
      type: date
      description: The time since the MongoDB resource was created.
      JSONPath: .metadata.creationTimestamp

  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
            - credentials
            - type
            - version
          oneOf:
            - required: [cloudManager]
            - required: [opsManager]
            - required: [project]
          properties:
            type:
              type: string
              enum: ["Standalone", "ReplicaSet", "ShardedCluster"]
            credentials:
              type: string
            project:
              type: string
              description: "DEPRECATED The name of a configMap in the same namespace"
            opsManager:
              type: object
              properties:
                configMapRef:
                  type: object
                  properties:
                    name:
                      type: string
            cloudManager:
              type: object
              properties:
                configMapRef:
                  type: object
                  properties:
                    name:
                      type: string

            version:
              type: string
              pattern: "^[0-9]+.[0-9]+.[0-9]+(-.+)?$"
            logLevel:
              type: string
              enum: ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"]
            persistent:
              type: boolean
            clusterName:
              type: string
              format: hostname
              description: "DEPRECATED Use clusterDomain instead"
            clusterDomain:
              type: string
              format: hostname

            additionalMongodConfig:
              type: object
              properties:
                net:
                  type: object
                  properties:
                    mode:
                      type: string
                      enum: ["disabled", "allowSSL", "preferSSL", "requireSSL", "allowTLS", "preferTLS", "requireTLS"]
                ssl:
                  type: object
                  properties:
                    mode:
                      type: string
                      enum: ["disabled", "allowSSL", "preferSSL", "requireSSL", "allowTLS", "preferTLS", "requireTLS"]

            exposedExternally:
              type: boolean

            # Generic PodSpec configuration
            podSpec:
              type: object
              properties:
                podTemplate:
                  type: object
                  properties:
                    spec:
                      type: object
                      properties:
                        podAntiAffinityTopologyKey:
                          type: string
                        cpu:
                          type: string
                        cpuRequests:
                          type: string
                        memory:
                          type: string
                        memoryRequests:
                          type: string
                        podAffinity:
                          type: object
                        nodeAffinity:
                          type: object
                        securityContext:
                          type: object
                        persistence:
                          type: object

            # TLS & authentication properties
            security:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    modes:
                      type: array
                      items:
                        type: string
                        enum: ["SCRAM", "X509"]
                    ignoreUnknownUsers:
                      type: boolean
                tls:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    ca:
                      type: string
                    additionalCertificateDomains:
                      type: array
                      items:
                        type: string

            # Sharded Cluster properties
            shardPodSpec:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    podAntiAffinityTopologyKey:
                      type: string
                    cpu:
                      type: string
                    cpuRequests:
                      type: string
                    memory:
                      type: string
                    memoryRequests:
                      type: string
                    podAffinity:
                      type: object
                    nodeAffinity:
                      type: object
                    securityContext:
                      type: object
                    persistence:
                      type: object

            mongosPodSpec:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    podAntiAffinityTopologyKey:
                      type: string
                    cpu:
                      type: string
                    cpuRequests:
                      type: string
                    memory:
                      type: string
                    memoryRequests:
                      type: string
                    podAffinity:
                      type: object
                    nodeAffinity:
                      type: object
                    securityContext:
                      type: object
                    persistence:
                      type: object
            configSrvPodSpec:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    podAntiAffinityTopologyKey:
                      type: string
                    cpu:
                      type: string
                    cpuRequests:
                      type: string
                    memory:
                      type: string
                    memoryRequests:
                      type: string
                    podAffinity:
                      type: object
                    nodeAffinity:
                      type: object
                    securityContext:
                      type: object
                    persistence:
                      type: object
            configServerCount:
              type: integer
            mongodsPerShardCount:
              type: integer
            mongosCount:
              minimum: 1
              type: integer
            shardCount:
              minimum: 1
              type: integer

      oneOf:
      # Standalone
      - properties:
          spec:
            properties:
              type:
                pattern: '^Standalone$'

      # ReplicaSet
      - properties:
          spec:
            properties:
              type:
                pattern: '^ReplicaSet$'
            required:
              - members

      # ShardedCluster
      - properties:
          spec:
            properties:
              type:
                pattern: '^ShardedCluster$'
            required:
              - configServerCount
              - mongodsPerShardCount
              - mongosCount
              - shardCount

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbusers.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDBUser
    plural: mongodbusers
    shortNames:
    - mdbu
    singular: mongodbuser
  additionalPrinterColumns:
    - name: State
      type: string
      description: The current state of the MongoDB User
      JSONPath: .status.phase
    - name: Age
      type: date
      description: The time since the MongoDB User resource was created
      JSONPath: .metadata.creationTimestamp
  validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              username:
                type: string
                description: "The username of the user"
              db:
                type: string
                description: "The database the user is stored in"
              project:
                type: string
                description: "The project the user belongs to"
              passwordSecretKeyRef:
                type: object
                properties:
                  name:
                    type: string
                  key:
                    type: string
                description: "DEPRECATED The project the user belongs to"
              mongodbResourceRef:
                type: object
                properties:
                  name:
                    type: string
                    description: "The name of a MongoDB resource in the same namespace"
              roles:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "The name of the role"
                    db:
                      type: string
                      description: "The db the role can act on"
                    passwordSecretKeyRef:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                  required:
                    - name
                    - db
            required:
              - username
              - db
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opsmanagers.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDBOpsManager
    plural: opsmanagers
    shortNames:
    - om
    singular: opsmanager
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      description: The number of replicas of MongoDBOpsManager.
      JSONPath: .spec.replicas
    - name: Version
      type: string
      description: The version of MongoDBOpsManager.
      JSONPath: .spec.version
    - name: Version (AppDB)
      type: string
      description: The version of Application Database  .
      JSONPath: .spec.applicationDatabase.version
    - name: State
      type: string
      description: The current state of the MongoDBOpsManager.
      JSONPath: .status.opsManager.phase
    - name: State (AppDB)
      type: string
      description: The current state of the MongoDBOpsManager Application Database.
      JSONPath: .status.applicationDatabase.phase
    - name: Age
      type: date
      description: The time since the MongoDBOpsManager resource was created.
      JSONPath: .metadata.creationTimestamp
    - name: Warnings
      type: string
      description: Warnings
      JSONPath: .status.warnings
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            version:
              type: string
            replicas:
              minimum: 1
              type: integer
            clusterName:
              type: string
              format: hostname
              description: "DEPRECATED Use clusterDomain instead"
            clusterDomain:
              type: string
              format: hostname
            externalConnectivity:
              type: object
              properties:
                type:
                  type: string
                  enum: ["LoadBalancer", "NodePort"]
                port:
                  type: integer
                loadBalancerIP:
                  type: string
                externalTrafficPolicy:
                  type: string
                  enum: ["Cluster", "Local"]
                annotations:
                  type: object
              required:
                - type
            backup:
              type: object
              properties:
                enabled:
                  type: boolean
                headDB:
                  type: object
                  properties:
                    storage:
                      type: string
                    storageClass:
                      type: string
                opLogStores:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mongodbResourceRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                      mongodbUserRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                            - name
                    required:
                      - name
                      - mongodbResourceRef
                s3Stores:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                    mongodbResourceRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    mongodbUserRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    pathStyleAccessEnabled:
                      type: boolean
                    s3BucketEndpoint:
                      type: string
                    s3BucketName:
                      type: string
                    s3SecretRef:
                      type: object
                      properties:
                        name: string
                    required:
                      - name
                      - mongodbResourceRef
                      - pathStyleAccessEnabled
                      - s3BucketEndpoint
                      - s3BucketName
                      - s3SecretRef

              required:
                - enabled
            applicationDatabase:
              type: object
              properties:
                passwordSecretKeyRef:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                  required:
                    - name
                members:
                  maximum: 50
                  minimum: 3
                  type: integer
                version:
                  type: string
                  pattern: "^[0-9]+.[0-9]+.[0-9]+(-.+)?$|^$"
                logLevel:
                  type: string
                  enum: ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"]
                persistent:
                  type: boolean
              required:
                - members
          required:
            - version
            - applicationDatabase

# This ClusterRole is necessary in order to use validating webhooks—these will
# prevent you from applying a variety of invalid resource definitions. The
# validating webhooks are optional so this can be removed if necessary.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-operator-mongodb-webhook
rules:
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - create
  - update
  - delete

{{ end }}
