---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.name }}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- end }}
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Values.operator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.operator.name }}
    spec:
      serviceAccountName: {{ .Values.operator.name }}
{{- if not .Values.managedSecurityContext }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
{{- end }}
{{- if .Values.registry.imagePullSecrets}}
      imagePullSecrets:
      - name: {{ .Values.registry.imagePullSecrets }}
{{- end }}

      containers:
      - name: {{ .Values.operator.name }}
        image: {{ .Values.registry.repository }}/{{ .Values.operator.name }}:{{ .Values.operator.version }}
        imagePullPolicy: {{ .Values.registry.pullPolicy }}
        env:
        - name: OPERATOR_ENV
          value: {{ .Values.operator.env }}
        - name: WATCH_NAMESPACE
{{- if .Values.operator.watchNamespace}}
          value: "{{ .Values.operator.watchNamespace }}"
{{- else }}
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- end }}
        - name: CURRENT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if eq .Values.managedSecurityContext true }}
        - name: MANAGED_SECURITY_CONTEXT
          value: 'true'
{{- end }}
        - name: MONGODB_ENTERPRISE_DATABASE_IMAGE
          value: {{ .Values.registry.repository }}/{{ .Values.database.name }}:{{ .Values.operator.version }}
        - name: IMAGE_PULL_POLICY
          value: {{ .Values.registry.pullPolicy }}
        - name: OPS_MANAGER_IMAGE_REPOSITORY
          value: {{ .Values.registry.repository }}/{{ .Values.opsManager.name }}
        - name: OPS_MANAGER_IMAGE_PULL_POLICY
          value: {{ .Values.registry.pullPolicy }}
        - name: APP_DB_IMAGE_REPOSITORY
          value: {{ .Values.registry.repository }}/{{ .Values.appDb.name }}

{{- if .Values.registry.imagePullSecrets }}
        - name: IMAGE_PULL_SECRETS
          value: {{ .Values.registry.imagePullSecrets }}
{{- end }}

{{- if .Values.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: debug-svc
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.debugPort }}
      port: 40000
      protocol: TCP
  selector:
    app: {{ .Values.operator.name }}
{{- end }}
