---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups:
  - mongodb.com
  resources:
  - "*"
  verbs:
  - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.operator.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}
