---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.name }}
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-appdb
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}
