---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
spec:
  members: 3
  version: 4.2.1
  service: my-service

  # Indicates featureCompatibilityVersion. This attribute will make the data
  # format to persist in a particular version, maybe older, allowing for
  # future downgrades if necessary.
  featureCompatibilityVersion: "3.6"

  # Please Note: The default Kubernetes cluster domain is `cluster.local`.
  # If your cluster has been configured with another domain, you can specify it
  # with the `clusterDomain` attribute.
  # clusterDomain: mycompany.net

  opsManager:
    configMapName:
      name: my-project
  credentials: my-credentials
  type: ReplicaSet

  # log level affects the level of logging for the agent. Use DEBUG cautiously as log file size may grow very quickly
  logLevel: WARN

  persistent: true
  podSpec:
    cpu: '0.25'
    # note: it's important to always specify memory otherwise wired tiger cache will be calculated incorrectly and
    # monitoring tools will report the size of Kubernetes node instead of the real size of the container
    memory: 512M
    # "multiple" persistence allows to mount different directories to different Persistent Volumes
    persistence:
      multiple:
        data:
          storage: 10Gi
        journal:
          storage: 1Gi
          labelSelector:
            matchLabels:
              app: "my-app"
        logs:
          storage: 500M
          storageClass: standard
