---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-sharded-cluster
spec:
  type: ShardedCluster

  shardCount: 2
  mongodsPerShardCount: 3
  mongosCount: 2
  configServerCount: 3

  version: 4.0.6-ent

  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials

  persistent: false

  # This will create a TLS enabled Sharded Cluster, which means that
  # all the traffic between Shards and clients will be encrypted using
  # TLS certificates.  These certificates will be generated on the fly
  # by the operator using the Kubernetes CA.
  security:
    # The operator will look for secrets with the following names:
    # mdb-my-sharded-cluster-mongos-cert
    # mdb-my-sharded-cluster-config-cert
    # mdb-my-sharded-cluster-<x>-cert
    # Where x is all numbers between 0 and the number of shards (excluded)
    certsSecretPrefix: mdb
    tls:
      ca: custom-ca
      enabled: true
