# Creates a MongoDB Replica Set with LDAP Authentication Enabled.
# LDAP is an Enterprise-only feature.

---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-ldap-enabled-replica-set
spec:
  type: ReplicaSet
  members: 3
  version: 4.0.4-ent

  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials

  security:
    authentication:
      enabled: true
      # Enabled LDAP Authentication Mode
      modes: ["LDAP"]

      # LDAP related configuration
      ldap:
        # Specify the hostname:port combination of one or
        # more LDAP servers
        servers:
        - "<ldap-server0>"
        - "<ldap-server1>"

        # Set to "tls" to use LDAP over TLS. Leave blank if
        # LDAP server does not accept TLS.
        transportSecurity: "tls"

        # ConfigMap containing a CA certificate that validates
        # the LDAP server's TLS certificate.
        caConfigMapRef:
          name: "<configmap-name>"
          key: "<configmap-entry-key>"

        # Specify the LDAP Distinguished Name to which
        # MongoDB binds when connecting to the LDAP server
        bindQueryUser: "cn=admin,dc=example,dc=org"

        # Specify the password with which MongoDB binds
        # when connecting to an LDAP server. This is a
        # reference to a Secret Kubernetes Object containing
        # one "password" key.
        bindQueryPasswordSecretRef:
          name: "<secret-name>"

        # Select True to validate the LDAP server configuration or False to skip validation.
        validateLDAPServerConfig: false

        # LDAP-formatted query URL template executed by MongoDB to obtain the LDAP groups that the user belongs to
        authzQueryTemplate: "{USER}?memberOf?base"

        # Maps the username provided to mongod or mongos for authentication to an LDAP Distinguished Name (DN).
        userToDNMapping: '[{match: "CN=mms-automation-agent,(.+),L=NY,ST=NY,C=US", substitution: "uid=mms-automation-agent,{0},dc=example,dc=org"}, {match: "(.+)", substitution:"uid={0},ou=groups,dc=example,dc=org"}]'

        # Specify how long an authentication request should wait before timing out. In milliseconds.
        timeoutMS: 10000

        # Specify how long MongoDB waits to flush the LDAP user cache. In seconds.
        userCacheInvalidationInterval: 30
