apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: opsmanagerreplicamembers
  annotations:
    description: >-
      Requires Ops Manager install to be 1 replica and 3 members

      The setting applicationDatabase.members should be 3 and replicas should be 0
spec:
  crd:
    spec:
      names:
        kind: OpsManagerReplicaMembers
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package opsmanagerreplicamembers

        default ops_conditions = true

        replicas := object.get(input.review.object.spec, "replicas", 0)

        dbmembers := object.get(input.review.object.spec.applicationDatabase, "members", 0)

        violation[{"msg": msg}] {
          not ops_conditions
          msg := sprintf("Ops Manager needs to have 1 replica and 3 members, current config is %v replica and %v members.", [replicas, dbmembers])
        }

        ops_conditions = false {
          replicas != 1
        }

        ops_conditions = false {
          dbmembers != 3
        }
