#
# This is a minimal config. To see all the options available, refer to the
# "extended" directory
#
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
spec:
  members: 3
  version: 4.0.10
  type: ReplicaSet

  project: my-project
  credentials: my-credentials

  persistent: false
